#!/usr/bin/env bash

# Enable debug mode if DEBUG is set
[[ -n $DEBUG ]] && set -x

red='\033[0;31m'
green='\033[0;32m'
reset='\033[0m'

INSTALL=false
VERSION=$1

# Check if the -i flag is provided for installation
if [[ $1 == "-i" ]]; then
  INSTALL=true
  VERSION=$2
fi

if [[ -z $VERSION ]]; then
  echo -e "${red}Error: no version specified!${reset}"
  echo -e "Usage: \`phpenv [VERSION]\` or \`phpenv -i [VERSION]\`"
  echo -e "Example: \`phpenv 81\` or \`phpenv -i 83\`"
  exit 1
fi

PHP_BIN="/usr/bin/php$VERSION"
PHPIZE_BIN="/usr/bin/phpize$VERSION"
PHP_FPM_BIN="/usr/bin/php-fpm$VERSION"
PHP_DBG_BIN="/usr/bin/phpdbg$VERSION"
PHP_CGI_BIN="/usr/bin/php-cgi$VERSION"
PHP_PEAR_BIN="/usr/bin/pear$VERSION"
PHP_PECL_BIN="/usr/bin/pecl$VERSION"

if [[ $INSTALL == true ]]; then
  echo -e "${green}Installing PHP $VERSION...${reset}"
  
  mkdir -p $HOME/bin
  mkdir -p $HOME/src
  cd $HOME/src
  
  REPO_URL="https://aur.archlinux.org/php$VERSION.git"
  echo -e "${green}Cloning from $REPO_URL...${reset}"
  git clone $REPO_URL
  cd php$VERSION
  makepkg -si
  
  # Wait a very long time (it literally compiles and installs php AND ALL MODULES)
  # enter sudo password after the compile step is done
  
  if [[ ! -x "$PHP_BIN" ]]; then
    echo -e "${red}Error: PHP $VERSION binary not found at $PHP_BIN after installation${reset}"
    exit 1
  fi
fi

# Check if PHP binaries exist for the specified version
if [[ ! -x "$PHP_BIN" ]]; then
  echo -e "${red}Error: PHP $VERSION binary not found at $PHP_BIN${reset}"
  exit 1
fi

# Remove existing links before creating new ones
for bin_link in php phpize php-fpm phpdbg php-cgi pear pecl; do
  [[ -L "$HOME/bin/$bin_link" ]] && rm -f "$HOME/bin/$bin_link"
done

# Create symbolic links
ln -s "$PHP_BIN" "$HOME/bin/php"
ln -s "$PHPIZE_BIN" "$HOME/bin/phpize"
ln -s "$PHP_FPM_BIN" "$HOME/bin/php-fpm"
ln -s "$PHP_DBG_BIN" "$HOME/bin/phpdbg"
ln -s "$PHP_CGI_BIN" "$HOME/bin/php-cgi"
ln -s "$PHP_PEAR_BIN" "$HOME/bin/pear"
ln -s "$PHP_PECL_BIN" "$HOME/bin/pecl"

echo -e "${green}Activated PHP $VERSION.${reset}"
php -v
